name: MIS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: ğŸ›’ Repository
      uses: actions/checkout@v4

    - name: ğŸ Python einrichten
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: ğŸ“¦ Dependencies
      run: |
        pip install -r requirements.txt
        pip install customtkinter requests

    - name: ğŸ” Validate
      run: |
        python -m py_compile app.py

    - name: ğŸ§ª CodeQL Analyse
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: ğŸ” CodeQL Scannen
      uses: github/codeql-action/analyze@v3
